config = {
    "IpRanges": '127.0.0.0 127.255.255.255 10.0.0.1 10.255.255.255',
    "globalPW": '<INSERT>',
    "salt": '<INSERT>',
    "currentYear": 2016,
    "mysql": {
        "user": "<INSERT>",
        "pass": "<INSERT>",
        "db": "<INSERT>",
        "host": "",
        "tables": {
            "config": "config",
            "regels":{
                "geboekt": "geboekt",
                "obligo": "obligo",
                "plan": "plan",
            },
            "salaris":{
                "geboekt": "salaris-geboekt",
                "obligo": "salaris-obligo",
                "plan": "salaris-plan",
            },
        },
    },
    "SAPkeys": {
        "types":{
            "ordernummer": "int",
            "kostensoort": "int",
            "kostensoortnaam": "varchar(255)",
            "kosten": "decimal(19,2)",
            "jaar": "int",
            "periode": "int",
            "omschrijving": "varchar(255)",
            "documentnummer": "varchar(255)",
            "invoerdatum": "varchar(255)",
            "personeelsnummer": "int",
            "personeelsnaam": "varchar(255)",
            "schaal": "varchar(255)",
            "trede": "int",
            "ordernaam": "varchar(255)",
        },
        "geboekt":{
            "ordernummer": "Order",
            "kostensoort": "Kostensoort",
            "kostensoortnaam": "Naam v. kostensoort",
            "kosten": "Waarde/CO-valuta",
            "jaar": "Boekjaar",
            "periode": "Periode",
            "omschrijving": "Omschrijving",
            "documentnummer": "Documentnummer",
            "invoerdatum": "Invoerdatum",
        },
        "obligo":{
            "ordernummer": "Order",
            "kostensoort": "Kostensoort",
            "kostensoortnaam": "Naam v. kostensoort",
            "kosten": "Waarde/CO-valuta",
            "jaar": "Boekjaar",
            "periode": "Periode",
            "omschrijving": "Omschrijving",
            "documentnummer": "Nr. referentiedoc.",
        },
        "plan":{
            "ordernummer": "Order",
            "kostensoort": "Kostensoort",
            "kostensoortnaam": "Naam v. kostensoort",
            "jaar": "Boekjaar",
            "documentnummer": "Documentnummer",
            "kosten": "Totaalwrd./vslg.val.",
        },
        "salaris":{
            "personeelsnummer": "PersNr",
            "personeelsnaam": "Naam",
            "schaal": "Schaal",
            "trede": "Tr.",
            "ordernummer": "Kostenpl.",
            "ordernaam": "Omschr. Kost.pl.",
            "kostensoort": "Gr.boek",
            "kostensoortnaam": "omschr.g.boekrek.",
            "kosten": "Bedrag",
            "invoerdatum": "Begda afr.",
        },
        "salaris_begroting":{
            "personeelsnummer": "Personeelsnummer",
            "personeelsnaam": "Naam",
            "trede": "Trede",
            "ordernummer": "Order",
            "schaal": "Schaal",
            "kosten": "Kosten",
        },
    }
}
