from .index import Index
from .report import Report
from .admin import Admin
from .login import Login
from .logout import Logout
from .graph import Graph
from .view import View
from .salaris import Salaris
from .orderlist import Orderlist
